version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dan
      - RABBITMQ_DEFAULT_PASS=Dan!
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
networks:
  app-network:
    name: app-network
